### ISSUE TITLE
TCP/IP

### ISSUE THREAD

**Issue by larsbrinkhoff** [PDP-10/tenex#10]
We need TCP/IP for TENEX.  Maybe it's already there, I haven't checked.

**Comment by larsbrinkhoff** [comment]
TCP/IP IMPLEMENTATIONS AND VENDORS GUIDE, 1985:
> SRI has implemented TCP/IP for the TENEX (FOONEX and  AUGUST) operating  system  running  on  DEC-10 KA or KI and F2, F3 or F4 Foonly processors.  It was adapted from the BBN and ISI versions of  TENEX  TCP/IP,  with contributions from Ed Taft of Xerox and Phil French of Tymshare, and resides in  the  operating  system.  It is largely upward-compatible with TOPS-20 implementations and fully compatible with AUGMENT.  Telnet, FTP, SMTP,  ICMP,  ECHO, TIME,  WHOIS,  and  NAME service are available although some are still under development.
> 
> This is an implementation done at BBN.    DARPA  has  dropped funding  for  continued  support for Tenex development, and thus the latest versions done for BBN and DEC  for  TOPS-20  are  not available for Tenex.

**Comment by larsbrinkhoff** [comment]
RFC 801, 1981:
> TCP4 and IP4 are available for use with the TENEX operating system running on a Digital KA10 processor with BBN pager.  TCP4 and IP4 are also available as part of TOPS20 Release 3A and Release 4 for the Digital KL10 and KL20 processors.

**Comment by b4** [comment]
Correction - TCP/IP is in 135-TENEX.

**Comment by larsbrinkhoff** [comment]
Indeed it is, thanks!
