### ISSUE TITLE
More TENEX?

### ISSUE THREAD

**Issue by b4** [PDP-10/tenex#2]
Is this more TENEX code, or is it something to run ATOP TENEX?

https://www.saildart.org/[KA,SYS]/

**Comment by larsbrinkhoff** [comment]
I read instructions in [DOC,AIL]TELLEM for installing SAIL (the language) in TENEX.

**Comment by rmaldersoniii** [comment]
I'll just point out that SAILDART is an archive of files from the Stanford Artificial Intelligence Laboratory (SAIL), retrieved from tapes created with DART (Disk Archive and Retrieval Tool). Although some of the tools created at SAIL can run under TENEX (such as the SAIL programming language), this is primarily a snapshot of everything ever done under WAITS, the SAIL PDP-6/PDP-10 operating system.

**Comment by b4** [comment]
This is more easily accessed from SUMEX dump, no need to keep this issue open.
