### ISSUE TITLE
SUDS

### ISSUE THREAD

**Issue by larsbrinkhoff** [PDP-10/tenex#4]
CAD system from Stanford.  Originally made by the AI lab.

Not sure it it's a TENEX thing.  Maybe WAITS.  But it seems to have been widely ported to DEC-10 and 20 systems.

**Comment by larsbrinkhoff** [comment]
I don't see much on saildart.org at this point, but it looks like there could be more in the future.

**Comment by rmaldersoniii** [comment]
SUDS was not a TENEX thing.  It originated under WAITS, as part of the SuperFOONLY project, SAIL's response to DEC's sloth in building a better PDP-10.  Two things came directly out of this effort, the Foonly company and the DECSYSTEM-20.

**Comment by larsbrinkhoff** [comment]
Maybe I should explain that I opened this issue as a reminder to @b4 to check for signs of SUDS anywhere.

**Comment by b4** [comment]
Seeing email references to it in the SUMEX archives, but not anything approaching sources.

I'll certainly need to look elsewhere for that.

You've checked SRI-NIC and the SRI-ARC DECUSLIB bits, right?

**Comment by larsbrinkhoff** [comment]
Not for SUDS specifially.  But I will.  I just stumbled across the SRI-ARC files yesterday.

**Comment by larsbrinkhoff** [comment]
@b4, here are some directory and file names to look out for:

DRAW, DATDRW, PC, DIPS, SIGSUB, SCNV, LAY, WLDEFS.

**Comment by b4** [comment]
mar@maelona /V/L/c/SUMEX> find . -name "*sigsub*"
mar@maelona /V/L/c/SUMEX> find . -name "*datdrw*"
mar@maelona /V/L/c/SUMEX> find . -name "*SCNV*"
mar@maelona /V/L/c/SUMEX> find . -name "*wldefs*"
mar@maelona /V/L/c/SUMEX> find . -name "*dips*"
mar@maelona /V/L/c/SUMEX> find . -name "*lay*"

No results except for the last one which brings up personal directories.

On Wed, Jan 31, 2018, at 20:04, Lars Brinkhoff wrote:
> @b4[1], here are some directory and file names to look out for:


> DRAW, DATDRW, PC, DIPS, SIGSUB, SCNV, LAY, WLDEFS.


> — You are receiving this because you were mentioned. Reply to this
> email directly, view it on GitHub[2], or mute the thread[3].> 

--
Madeline Autumn-Rose
  b4@gewt.net



Links:

  1. https://github.com/b4
  2. https://github.com/PDP-10/tenex/issues/4#issuecomment-362152074

**Comment by larsbrinkhoff** [comment]
Thanks!

I'll close this now, because it's not related to TENEX.
